site_name: 'Documentation for CTXCloudApi'
site_description: 'Documentation for CTXCloudApi'
site_author: 'Pierre Smit'
site_url: 'https://smitpi.github.io/CTXCloudApi'

theme:
  name: 'windmill'
  language: 'en'


repo_name: 'smitpi/CTXCloudApi'
repo_url: 'https://github.com/smitpi/CTXCloudApi'

copyright: '(c) 2021 Pierre Smit. All rights reserved.'

